[package]
name = "simpl"
version = "0.1.0-alpha.1"
authors = ["Drazen Urch <drazen@urch.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
